function plotVMAxis( axis, activeWearTimes, wearTimes )
%PLOTVMAXIS Plot the active wear times on a figure
%       PLOTVMAXIS(axis, activeWearTimes, wearTimes ) Plots
%       the wear times on the same figure as the raw data. The raw data will be
%       the blue lines, the red line will be the active wear times, and the
%       cyan line will be the wear intervals.
%       Inputs:
%           axis: The vector magnitude axis to plot
%
%           activeWearTimes: The Nx2 matrix generated by identifyActiveAreas
%
%           wearTimes: The Nx2 matrix of wear time periods

INTERVAL = 60;

% Create the vector of active or nonactive points
activeVector = zeros(length(axis), 1);
for i = 1:size(activeWearTimes, 1)
    height = mean(axis(activeWearTimes(i,1):activeWearTimes(i,2)));
    activeVector(activeWearTimes(i,1):activeWearTimes(i,2)) = height;
end

% Plot the wear time also
wearTimesVector = zeros(length(axis), 1);
wearHeight = max(axis) / 2;
for i = 1:size(wearTimes, 1)
    startpos = min(wearTimes(i,1) * INTERVAL, length(axis));
    endpos = min(wearTimes(i,2) * INTERVAL, length(axis));
    wearTimesVector(startpos:endpos) = wearHeight;
end

f1 = figure; % open a new window
hold on;
plot(axis, '-b');
plot(activeVector, '-r', 'LineWidth', 2);
plot(wearTimesVector, '-c', 'LineWidth', 2);
hold off;

% Set labels and display properly
xlabel('Seconds');  % X-axis represents seconds
ylabel('Activity Count');    % Y-axis represents the magnitude measured

% First line plotted was for raw data, second was to mark the active regions
legend('Raw accelerometer data', 'Active Regions', 'Wear Time Periods');
title('Wear Times and Bouts for VM Axis');

