function plotWearTimes(axis, wearTimes, intervalTime)
%PLOTWEARTIMES Plot the wear area on a figure
%      PLOTWEARTIMES(axis, wearTimes, intervalTime) Plots the wear time region
%      found using the findWearTimes function.
%      Inputs:
%          axis: The raw data axis from the accelerometer
%          wearTimes: The boolean vector generated by findWearTimes
%          intervalTime: The length of the interval, in seconds, used to find
%              the wear times.

f1 = figure;        % open a new window
plot(axis, '-b');   % plot the actual axis
hold on;            % allow us to plot again on the same figure

% Check if the interval was supplied, if not then assume 1 minute with the data
% being at 1 second epochs
if ~exist('intervalTime', 'var')
    fprintf('No time interval supplied, so using the default of 1 minute\n');
    intervalTime = 60;
end

% Expand the activeAreas matrix back from one minute epochs to one second
secondEpochWearTimes = zeros(length(axis), 1);
fprintf('Creating wear time vector... ');
for i = 1:length(wearTimes)
    startpos = i*intervalTime;
    endpos = min((i*intervalTime)+intervalTime, length(axis));

    if wearTimes(i) == 1
        secondEpochWearTimes(startpos:endpos) = 50;
    else
        % This else should be unnecessary
        secondEpochWearTimes(startpos:endpos) = 0;
    end
end
fprintf('Done.\n');

% Now plot it
plot(secondEpochWearTimes, '-r', 'LineWidth', 2);

% Set labels and display properly
xlabel('Seconds');          % X-axis represents seconds
ylabel('Activity Count');   % Y-axis represents the magnitude measured
legend('Actual data', 'Wear Region');      % Display info
title('Wear Region of Data');

hold off;
