% This is from the cliques formed by correlations on the training data

% Features from the 0.8 correlation cliques
featsToKeep8 = { 'axis1_proportion', ...
				 'axis2_proportion', ...
				 'axis3_proportion', ...
				 'axis1_Bout_length_avg', ...
				 'axis1_Gap_between_bouts_length_avg', ...
				 'axis1_Bucket_for_half_life', ...
				 'VM_Activity_count_per_wear_time_avg', ...
				 'VM_Activity_counts_per_minute_per_bout_avg', ...
				 'VM_Bout_length_avg', ...
				 'VM_Gap_between_bouts_length_avg', ...
				 'VM_Number_of_bouts_per_wear_time_avg', ...
				 'VM_Number_of_bouts_per_wear_time_std', ...
				 'VM_Number_of_wear_times', ...
				 'VM_Total_number_of_bouts' };

% Features from the 0.7 correlation cliques
featsToKeep7 =  { 'axis1_proportion', ...
				  'axis2_proportion', ...
				  'axis3_proportion', ...
				  'VM_Number_of_wear_times', ...
				  'VM_Total_number_of_bouts', ...
				  'VM_Number_of_bouts_per_wear_time_avg', ...
				  'VM_Activity_count_per_wear_time_std', ...
				  'VM_Bout_length_avg', ...
				  'axis1_Gap_between_bouts_length_avg', ...
				  'VM_Gap_between_bouts_length_std', ...
				  'VM_Activity_count_per_wear_time_avg', ...
				  'VM_Activity_counts_per_minute_per_bout_avg' };

% Features from the 0.6 correlation cliques
featsToKeep6 = { 'axis1_proportion', ...
				 'axis2_proportion', ...
				 'axis3_proportion', ...
				 'VM_Number_of_wear_times', ...
				 'VM_Total_number_of_bouts', ...
				 'VM_Number_of_bouts_per_wear_time_avg', ...
				 'VM_Activity_count_per_wear_time_std', ...
				 'VM_Activity_counts_per_minute_per_bout_avg', ...
				 'VM_Bout_length_avg', ...
				 'VM_Gap_between_bouts_length_avg' };
