function [] =  initStats()
%INITSTATS Initialize the variable containing the stats found (names)

global stats_names

stats_names = { ...
    'Number_of_wear_times', ...
    'Total_number_of_bouts', ...
    'Number_of_bouts_per_wear_time_avg', ...
    'Number_of_bouts_per_wear_time_std', ...
    'Activity_counts_per_minute_per_bout_avg', ...
    'Activity_counts_per_minute_per_bout_std', ...
    'Bout_length_avg', ...
    'Bout_length_std', ...
    'Gap_between_bouts_length_avg', ...
    'Gap_between_bouts_length_std', ...
    'Activity_count_per_wear_time_avg', ...
    'Activity_count_per_wear_time_std', ...
    'Bucket_for_half_life', ...
    'Counts_per_min_for_half_life', ...
};

end
