% This script blocks the interactive portion of Matlab while it waits for the
% jobs to finish

% Run it for baseline1 with pruning
j1 = batch(@exportAll, ...  % the function we are going to call
           0, ...           % the amount of outputs expected
           { ... arguments for the exportAll function
               '/media/My Passport/LIFE_BASELINE_ACCELEROMETRY/baseline1', ...
               '../output/baseline1_pruned.csv', ...
               true ...
           }, ...
           'matlabpool', 0);    % run it on the pool with 0 extra workers

% Without pruning
j2 = batch(@exportAll, ...
           0, ...
           { ...
               '/media/My Passport/LIFE_BASELINE_ACCELEROMETRY/baseline1', ...
               '../output/baseline1_regular.csv', ...
               false ...
           }, ...
           'matlabpool', 0);

% Run it for baseline2 with pruning
j3 = batch(@exportAll, ...
           0, ...
           { ...
               '/media/My Passport/LIFE_BASELINE_ACCELEROMETRY/baseline2', ...
               '../output/baseline2_pruned.csv', ...
               true ...
           }, ...
           'matlabpool', 0);

% Without pruning
j4 = batch(@exportAll, ...
           0, ...
           { ...
               '/media/My Passport/LIFE_BASELINE_ACCELEROMETRY/baseline2', ...
               '../output/baseline2_regular.csv', ...
               false ...
           }, ...
           'matlabpool', 0);

% Let them all finish
wait(j1);
wait(j2);
wait(j3);
wait(j4);

diary(j1, '../output/baseline1_regular.log');
diary(j2, '../output/baseline1_pruned.log');
diary(j3, '../output/baseline2_regular.log');
diary(j4, '../output/baseline2_pruned.log');
