% This script blocks the interactive portion of Matlab while it waits for the
% jobs to finish

% Run it for baseline1
j1 = batch(@exportAllControl, ...  % the function we are going to call
           0, ...                  % the amount of outputs expected
           { ... arguments for the exportAll function
               '/media/My Passport/LIFE_BASELINE_ACCELEROMETRY/baseline1', ...
               '../output/baseline1_control.csv', ...
           }, ...
           'matlabpool', 0);    % run it on the pool with 0 extra workers

% Run it for baseline2 with pruning
j2 = batch(@exportAllControl, ...
           0, ...
           { ...
               '/media/My Passport/LIFE_BASELINE_ACCELEROMETRY/baseline2', ...
               '../output/baseline2_control.csv', ...
           }, ...
           'matlabpool', 0);

% Let them all finish
wait(j1);
wait(j2);

diary(j1, '../output/baseline1_control.log');
diary(j2, '../output/baseline2_control.log');
